### ISSUE TITLE
Tobii provider crashes on startup

### ISSUE THREAD

**Issue by evilC** [evilC/IOWrapper#24]
Fresh Win10 x64 system, suspect due to missing VC runtimes or .NET?  
Only Tobii affected, deleting provider allows UCR to load  

```
2019-02-13 14:23:38.2582 INFO Launching UCR 
2019-02-13 14:23:40.4925 ERROR Failed to load context.xml 
2019-02-13 14:23:40.5238 DEBUG Start bind mode 
2019-02-13 14:23:49.0192 ERROR Failed to load context.xml 
2019-02-13 14:23:49.0348 DEBUG Start bind mode 
2019-02-13 14:27:07.5240 INFO UCR is already running, sending args: {} 
2019-02-13 14:30:43.0255 INFO Launching UCR 
2019-02-13 14:30:45.2860 ERROR Failed to load context.xml 
2019-02-13 14:30:45.4251 FATAL The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Unable to load DLL 'Tobii.EyeX.Client.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Resulting in: An exception occurred while trying to create an instance of type 'Core_Tobii_Interaction.Core_Tobii_Interaction'.

Resulting in: Cannot activate part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot get export 'Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' from part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot set import 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' on part 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)'.
Element: HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)
 System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Unable to load DLL 'Tobii.EyeX.Client.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Resulting in: An exception occurred while trying to create an instance of type 'Core_Tobii_Interaction.Core_Tobii_Interaction'.

Resulting in: Cannot activate part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot get export 'Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' from part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot set import 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' on part 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)'.
Element: HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)

   at System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.AttributedModelServices.ComposeParts(CompositionContainer container, Object[] attributedParts)
   at HidWizards.IOWrapper.Core.GenericMEFPluginLoader`1..ctor(String basePath)
   at HidWizards.IOWrapper.Core.IOController..ctor()
   at HidWizards.UCR.Core.Context.Init() in C:\projects\ucr\UCR.Core\Context.cs:line 57
   at HidWizards.UCR.Core.Context.Load(List`1 pluginTypes) in C:\projects\ucr\UCR.Core\Context.cs:line 125
   at HidWizards.UCR.App.InitializeUcr()
   at HidWizards.UCR.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HidWizards.UCR.App.Main()
2019-02-13 14:38:08.8667 INFO Launching UCR 
2019-02-13 14:38:11.1557 ERROR Failed to load context.xml 
2019-02-13 14:38:11.6051 INFO UCR is already running, sending args: {} 
2019-02-13 14:38:11.6650 FATAL The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Unable to load DLL 'Tobii.EyeX.Client.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Resulting in: An exception occurred while trying to create an instance of type 'Core_Tobii_Interaction.Core_Tobii_Interaction'.

Resulting in: Cannot activate part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot get export 'Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' from part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot set import 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' on part 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)'.
Element: HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)
 System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Unable to load DLL 'Tobii.EyeX.Client.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Resulting in: An exception occurred while trying to create an instance of type 'Core_Tobii_Interaction.Core_Tobii_Interaction'.

Resulting in: Cannot activate part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot get export 'Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' from part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot set import 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' on part 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)'.
Element: HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)

   at System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.AttributedModelServices.ComposeParts(CompositionContainer container, Object[] attributedParts)
   at HidWizards.IOWrapper.Core.GenericMEFPluginLoader`1..ctor(String basePath)
   at HidWizards.IOWrapper.Core.IOController..ctor()
   at HidWizards.UCR.Core.Context.Init() in C:\projects\ucr\UCR.Core\Context.cs:line 57
   at HidWizards.UCR.Core.Context.Load(List`1 pluginTypes) in C:\projects\ucr\UCR.Core\Context.cs:line 125
   at HidWizards.UCR.App.InitializeUcr()
   at HidWizards.UCR.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HidWizards.UCR.App.Main()
2019-02-13 14:39:06.7592 INFO Launching UCR 
2019-02-13 14:39:09.0013 ERROR Failed to load context.xml 
2019-02-13 14:39:09.1594 FATAL The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Unable to load DLL 'Tobii.EyeX.Client.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Resulting in: An exception occurred while trying to create an instance of type 'Core_Tobii_Interaction.Core_Tobii_Interaction'.

Resulting in: Cannot activate part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot get export 'Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' from part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot set import 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' on part 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)'.
Element: HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)
 System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Unable to load DLL 'Tobii.EyeX.Client.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Resulting in: An exception occurred while trying to create an instance of type 'Core_Tobii_Interaction.Core_Tobii_Interaction'.

Resulting in: Cannot activate part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot get export 'Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' from part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot set import 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' on part 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)'.
Element: HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)

   at System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.AttributedModelServices.ComposeParts(CompositionContainer container, Object[] attributedParts)
   at HidWizards.IOWrapper.Core.GenericMEFPluginLoader`1..ctor(String basePath)
   at HidWizards.IOWrapper.Core.IOController..ctor()
   at HidWizards.UCR.Core.Context.Init() in C:\projects\ucr\UCR.Core\Context.cs:line 57
   at HidWizards.UCR.Core.Context.Load(List`1 pluginTypes) in C:\projects\ucr\UCR.Core\Context.cs:line 125
   at HidWizards.UCR.App.InitializeUcr()
   at HidWizards.UCR.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HidWizards.UCR.App.Main()
2019-02-13 14:39:09.1504 INFO UCR is already running, sending args: {} 
2019-02-13 14:39:12.6615 INFO Launching UCR 
2019-02-13 14:39:14.9093 ERROR Failed to load context.xml 
2019-02-13 14:39:15.0535 FATAL The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Unable to load DLL 'Tobii.EyeX.Client.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Resulting in: An exception occurred while trying to create an instance of type 'Core_Tobii_Interaction.Core_Tobii_Interaction'.

Resulting in: Cannot activate part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot get export 'Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' from part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot set import 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' on part 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)'.
Element: HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)
 System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Unable to load DLL 'Tobii.EyeX.Client.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Resulting in: An exception occurred while trying to create an instance of type 'Core_Tobii_Interaction.Core_Tobii_Interaction'.

Resulting in: Cannot activate part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot get export 'Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' from part 'Core_Tobii_Interaction.Core_Tobii_Interaction'.
Element: Core_Tobii_Interaction.Core_Tobii_Interaction (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  Core_Tobii_Interaction.Core_Tobii_Interaction -->  DirectoryCatalog (Path=".\Providers\Core_Tobii_Interaction")

Resulting in: Cannot set import 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider")' on part 'HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)'.
Element: HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider).Plugins (ContractName="HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider") -->  HidWizards.IOWrapper.Core.GenericMEFPluginLoader(HidWizards.IOWrapper.ProviderInterface.Interfaces.IProvider)

   at System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.AttributedModelServices.ComposeParts(CompositionContainer container, Object[] attributedParts)
   at HidWizards.IOWrapper.Core.GenericMEFPluginLoader`1..ctor(String basePath)
   at HidWizards.IOWrapper.Core.IOController..ctor()
   at HidWizards.UCR.Core.Context.Init() in C:\projects\ucr\UCR.Core\Context.cs:line 57
   at HidWizards.UCR.Core.Context.Load(List`1 pluginTypes) in C:\projects\ucr\UCR.Core\Context.cs:line 125
   at HidWizards.UCR.App.InitializeUcr()
   at HidWizards.UCR.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HidWizards.UCR.App.Main()

```

**Comment by evilC** [comment]
[Visual C++ Redistributable for Visual Studio 2012](https://www.microsoft.com/en-us/download/details.aspx?id=30679) is required.  
This is all handled in the NuGet package, I do not seem to be able to control it
